theme: jekyll-theme-minimal
title: MatÃ­as Celestino SchrÃ¶der | ğŸ’»ğŸ¤“
description: 
  - Celular: +54 9 351 521 2248 
  - Email: matischroder99@gmail.com  
  - Linkedin: [MatÃ­as SchrÃ¶der](https://www.linkedin.com/in/matischroder/)
github:
  is_project_page: false
avatar: /assets/img/cv.jpeg
  
